package nl.bioinf.io;

import nl.bioinf.model.ComparisonResults;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * Writes a file containing the results of comparing the beta values of different samples / chromosomes / genes.
 * it does this using data ({@link nl.bioinf.comparing.MethylationArraySampleComparer})
 * generated by {@link nl.bioinf.comparing.MethylationArrayPosComparer}.
 */
public class ComparisonFileWriter {

    private static final Logger logger = LogManager.getLogger();
    private final ComparisonResults data;
    private final Path pathFileOutput;

    /**
     *
     * @param data           {@link ComparisonResults}
     * @param filePathOutput Path to write the resulting file to.
     */
    public ComparisonFileWriter(ComparisonResults data, Path filePathOutput) {
        this.data = data;
        pathFileOutput = filePathOutput;
    }

    /**
     * Writes the data from a {@link ComparisonResults} instance to a file.
     *
     * @throws IOException
     */
    public void writeData() throws IOException {
        File filePath = new File(pathFileOutput.toUri());
        logger.info("Writing data to file: {}.", filePath);

        try (BufferedWriter newFile = new BufferedWriter(new FileWriter(filePath))) {

            newFile.write(createHeader());
            newFile.write(createCompareFileBody());

        } catch (IOException ex) {
            logger.error("""
                            Unexpected IO error when writing to file: '{}'.\s
                            Exception occurred: '{}'.
                            """,
                    ex.getMessage(), ex);
            throw ex;
        }
        logger.info("Output generated at: {}", filePath);

    }

    private String createHeader() {
        StringBuilder header = new StringBuilder();
        header.append("Variable1,Variable2");
        for (String method : data.getStatisticMethods()) {
            header.append(",").append(method);
        }
        header.append(String.format("%n"));

        return header.toString();
    }

    private String createCompareFileBody() {
        int sampleIndex = 0;
        Map<String, List<Double>> statisticsResults = data.getStatisticsData();
        StringBuilder newFileBody = new StringBuilder();
        for (String sample : data.getSampleVersusSampleNames()) {
            newFileBody.append(sample);
            for (String method : data.getStatisticMethods()) {
                newFileBody.append(",").append(statisticsResults.get(method).get(sampleIndex));
            }
            newFileBody.append(String.format("%n"));
            sampleIndex++;
        }

        return newFileBody.toString();
    }
}
